/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ErsteAnwendung */

#ifndef _Included_ErsteAnwendung
#define _Included_ErsteAnwendung
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
