/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_meins_jni_StrLen */

#ifndef _Included_org_meins_jni_StrLen
#define _Included_org_meins_jni_StrLen
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_meins_jni_StrLen
 * Method:    strlen
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_meins_jni_StrLen_strlen
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
